### ISSUE TITLE
Need for help!

### ISSUE THREAD

**Issue by roTokyo** [NiklasEi/jekyll-exif-data#1]
I would like to use your pluin but I'm unable to make it working.

Now, I got this error:
   Liquid Warning: Liquid syntax error (line 17): Unexpected character / in "{{ assets/images/ori/01.jpg | exif: 'model'}}" in index.html
  Liquid Exception: undefined method `getbyte' for nil:EXIFR::JPEG::Reader in index.html
bundler: failed to load command: jekyll (/usr/local/lib/ruby/gems/2.6.0/bin/jekyll)
NoMethodError: undefined method `getbyte' for nil:EXIFR::JPEG::Reader
  /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/delegate.rb:87:in `method_missing'
  /usr/local/lib/ruby/gems/2.6.0/gems/exifr-1.3.6/lib/exifr/jpeg.rb:101:in `examine'
  /usr/local/lib/ruby/gems/2.6.0/gems/exifr-1.3.6/lib/exifr/jpeg.rb:36:in `initialize'
  /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-exif-data-0.0.3/lib/jekyll/exif-data.rb:9:in `new'
  /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-exif-data-0.0.3/lib/jekyll/exif-data.rb:9:in `exif'
  /usr/local/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/strainer.rb:56:in `invoke'
  /usr/local/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/context.rb:86:in `invoke'
  /usr/local/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/variable.rb:84:in `block in render'
  /usr/local/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `each'
  /usr/local/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `inject'
  /usr/local/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `render'
  /usr/local/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
  /usr/local/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:80:in `render'
  /usr/local/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
  /usr/local/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
  /usr/local/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
  /usr/local/lib/ruby/gems/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
  /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:35:in `block (3 levels) in render!'
  /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:49:in `measure_counts'
  /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:34:in `block (2 levels) in render!'
  /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:53:in `measure_bytes'
  /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:33:in `block in render!'
  /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:60:in `measure_time'
  /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:32:in `render!'
  /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:127:in `render_liquid'
  /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:80:in `render_document'
  /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:63:in `run'
  /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:523:in `render_regenerated'
  /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:516:in `block in render_pages'
  /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:515:in `each'
  /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:515:in `render_pages'
  /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:202:in `render'
  /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:76:in `process'
  /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:28:in `process_site'
  /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:65:in `build'
  /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:36:in `process'
  /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
  /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `each'
  /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
  /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
  /usr/local/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /usr/local/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /usr/local/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /usr/local/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /usr/local/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.6.0/bin/jekyll:23:in `load'
  /usr/local/lib/ruby/gems/2.6.0/bin/jekyll:23:in `<top (required)>'

exifr is installed and working ... I tested with:
irb(main):005:0> EXIFR::JPEG.new('assets/images/ori/01.jpg').model
=> "X-E1"
irb(main):006:0> 

an for the "/" character I'm following your examples ... I think ...

Can you help me where I'm wrong?

Thank you!

**Comment by NiklasEi** [comment]
Hey,
could it be that you are missing ticks around the path? Please try it again with `{{ 'assets/images/ori/01.jpg' | exif: 'model'}}`.

**Comment by roTokyo** [comment]
Thank you for your quick and kind reply, I really appreciate!
Unfortunately not working and the error is exactly the same but the first 6 lines that I'll attach:

  Liquid Exception: No such file or directory @ rb_sysopen - assets/images/ori/01.jpg in index.html
bundler: failed to load command: jekyll (/usr/local/lib/ruby/gems/2.6.0/bin/jekyll)
Errno::ENOENT: No such file or directory @ rb_sysopen - assets/images/ori/01.jpg
  .../exifr-1.3.6/lib/exifr/jpeg.rb:34:in `initialize'
  .../exifr-1.3.6/lib/exifr/jpeg.rb:34:in `open'
  .../exifr-1.3.6/lib/exifr/jpeg.rb:34:in `initialize'
... (the same error as above) ...

any idea how can be solved?

**Comment by NiklasEi** [comment]
> Liquid Exception: No such file or directory

Now it looks like the path to the image might not be correct. Is the code on GitHub? Then I could take a look at the project.

**Comment by roTokyo** [comment]
No, but I'll add a simplified version in few minutes.

**Comment by roTokyo** [comment]
You can find it here: [https://github.com/roTokyo/test](https://github.com/roTokyo/test)

**Comment by NiklasEi** [comment]
Since your root directory does not include your `assets` folder you need to adjust the path.

This should work: `{{ 'source/assets/images/ori/01.jpg' | exif: 'model'}}`

**Comment by roTokyo** [comment]
Thank you very much! It perfectly works.
Really appreciate your kindness.

**Comment by NiklasEi** [comment]
No problem, thanks for using my plugin ;)
