### ISSUE TITLE
doesn't run on github

### ISSUE THREAD

**Issue by jphconstantin** [NiklasEi/jekyll-exif-data#2]
Hello,
I use the 0.0.3 version, jekyll version 4.1.0
Run correctly on my local machine (Linux)
Doesn't run when I deploy on github !

I applied carefully the readme.
What I could forget ? dependencies ?
My code:
` 
   Modèle: {{ include.content | exif: 'model' }}
    Prise de vue: {{ include.content | exif: 'date_time' | date: "%d-%m-%Y" }}
    Vitesse: {{ include.content | exif: 'exposure_time.to_s' }}
    Ouverture: {{ include.content | exif: 'f_number.to_f' }}
`    
where **include.content** is a image path.

**Comment by jphconstantin** [comment]
> GitHub Pages cannot build sites using unsupported plugins. If you want to use unsupported plugins, generate your site locally and then push your site's static files to GitHub.

This is the resaon and the solution ?

**Comment by NiklasEi** [comment]
I have never used Github Pages with Jekyll before, but it sounds like this might be the issue, yes.
If you are looking for a free way of publishing the website after every push to your repository you could also consider netlify. At least I know that the plugin works there.

**Comment by jphconstantin** [comment]
Thank you
