### ISSUE TITLE
Does this support PNGs as well?

### ISSUE THREAD

**Issue by 888ba8** [NiklasEi/jekyll-exif-data#3]
Hi, does this support PNGs as well?

**Comment by NiklasEi** [comment]
As far as I remember I have used it with PNGs before, yes. Have you tried and encountered issues?

**Comment by 888ba8** [comment]
Hi @NiklasEi The EXIFR which is being used by your tool does not support PNGs. See https://talk.jekyllrb.com/t/using-png-exiftags-in-jekyll-p-s-jpgs-are-working-fine/5485/

**Comment by NiklasEi** [comment]
In that case, I must be mistaken. I have to admit that I have not used Jekyll or this plugin in a while.
We would have to switch the used EXIF reader then. Not sure I will have time for that in the near future.

**Comment by NiklasEi** [comment]
Did you get it to work with PNGs or found another solution?
